cargo-features = ["per-package-target"]

[package]
name = "agb_template"
version = "0.1.0"
authors = [""]
edition = "2021"
forced-target = "thumbv4t-none-eabi"

[dependencies]
agb = "0.20.5"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
lto = "fat"
debug = true
