[package]
name = "map-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
tiled = "0.12.0"
util = { path = "../util" }
bresenham = "0.1.1"
quote = "1"
proc-macro2 = "1"
phf_codegen = "0.11.1"
nalgebra = "0.33.0"
agb_fixnum = { version = "0.21.0" }
itertools = "0.13.0"
